a.out:
	gcc pc-sem.c -lpthread

join:
	gcc join-sum.c -lpthread

fish:
	gcc fish-sem.c -lpthread -o fish

philosopher:
	gcc philosopher.c -lpthread -o philosopher


.PHONY: clean a.out join fish
clean: 
	rm a.out fish philosopher